services:
  broker1:
    image: apache/kafka:3.9.0
    container_name: broker1
    ports:
      - "10002:10002"
    environment:
      - CLUSTER_ID=kjk2323sfkdsfsd
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker1:9093,2@broker2:9093,3@broker3:9093
      - KAFKA_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL_LOCALHOST://:10002
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://broker1:9092,EXTERNAL_LOCALHOST://localhost:10002
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_LOCALHOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL_LOCALHOST
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

  broker2:
    image: apache/kafka:3.9.0
    container_name: broker2
    ports:
      - "10003:10003"
    environment:
      - CLUSTER_ID=kjk2323sfkdsfsd
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker1:9093,2@broker2:9093,3@broker3:9093
      - KAFKA_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL_LOCALHOST://:10003
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://broker2:9092,EXTERNAL_LOCALHOST://localhost:10003
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_LOCALHOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL_LOCALHOST
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
    
  broker3:
    image: apache/kafka:3.9.0
    container_name: broker3
    ports:
      - "10004:10004"
    environment:
      - CLUSTER_ID=kjk2323sfkdsfsd
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker1:9093,2@broker2:9093,3@broker3:9093
      - KAFKA_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL_LOCALHOST://:10004
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://broker3:9092,EXTERNAL_LOCALHOST://localhost:10004
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL_LOCALHOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CLIENT_LISTENER_NAME=EXTERNAL_LOCALHOST
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
